const KEY='job_tracker_desktop_v1';
const DAILY_QUOTE_KEY='job_tracker_daily_quote_v1';
const STAGES=['已投递','测评','笔试','面试','Offer','已结束'];
const STATUSES=['等待结果','已通过','未通过','已放弃','已结束'];
const TYPES=['测评','笔试','面试','Offer','其他'];
const CHANNELS=['官网','Boss直聘','实习僧','牛客','猎聘','智联招聘','前程无忧','校园招聘平台','内推','其他'];
const tones={'等待结果':'amber','已通过':'cyan','未通过':'red','已放弃':'gray','已结束':'gray','已投递':'blue','测评':'purple','笔试':'amber','面试':'cyan','Offer':'green'};
let state=load(), page='home', selectedId=null, mailResult=null, applicationHeatmapMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let localDataReady=false,dailyQuoteRequest=null;
function initial(){return{applications:[],events:[],settings:{apiUrl:'https://api.deepseek.com',model:'deepseek-chat',apiKey:''}}}
function normalizeApplicationRecords(data){let changed=false;(data.applications||[]).forEach(application=>{if(application.stage==='准备投递'){application.stage='已投递';changed=true}if(!application.status||['进行中','等待安排'].includes(application.status)){application.status='等待结果';changed=true}});return changed}
function load(){try{const cached=JSON.parse(localStorage.getItem(KEY)||'{}');if(cached.settings)delete cached.settings.apiKey;normalizeApplicationRecords(cached);localStorage.setItem(KEY,JSON.stringify(cached));return Object.assign(initial(),cached)}catch{return initial()}}
function save(){
  const businessState=JSON.parse(JSON.stringify(state));if(businessState.settings)delete businessState.settings.apiKey;
  localStorage.setItem(KEY,JSON.stringify(businessState));
  if(window.isOnlineMode&&!window.currentUser)return;
  fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(businessState),keepalive:true})
    .catch(()=>{});
  fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:state.settings.apiKey||''}),keepalive:true}).catch(()=>{});
}
async function loadFromLocalFile(){
  try{
    const response=await fetch('/api/data',{cache:'no-store'});
    if(!response.ok)throw new Error(`HTTP ${response.status}`);
    const result=await response.json();
    if(result.exists&&result.data){
      const configResponse=await fetch('/api/config',{cache:'no-store'}),localConfig=configResponse.ok?await configResponse.json():{};
      state={...initial(),...result.data,settings:{...initial().settings,...(result.data.settings||{}),apiUrl:localConfig.apiUrl||result.data.settings?.apiUrl||initial().settings.apiUrl,model:localConfig.model||result.data.settings?.model||initial().settings.model,apiKey:localConfig.apiKey||''}};
      const migrated=normalizeApplicationRecords(state);
      const cached=JSON.parse(JSON.stringify(state));delete cached.settings.apiKey;localStorage.setItem(KEY,JSON.stringify(cached));
      document.documentElement.dataset.theme=state.settings.theme||'blue';
      render();
      if(migrated)save();
    }else{
      state=initial();
      localStorage.setItem(KEY,JSON.stringify(state));
      document.documentElement.dataset.theme=state.settings.theme||'blue';
      render();
      save();
    }
  }catch(error){
    console.warn('本地文件暂不可用，已使用浏览器缓存：',error);
  }
}
function id(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(16).slice(2,7)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function nowText(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`}
function today(){return nowText().slice(0,10)}
function formatDate(v){if(!v)return '未设置';const d=new Date(v.replace(' ','T'));if(isNaN(d))return v;return `${d.getMonth()+1}月${d.getDate()}日 ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function eventHasRange(event){return Boolean(String(event?.endsAt||'').trim())}
function eventRecordAt(event){return eventHasRange(event)&&event.completed?(event.completedAt||event.endsAt||event.startsAt):event.startsAt}
function eventDeadlineAt(event){return eventHasRange(event)&&!event.completed?event.endsAt:eventRecordAt(event)}
function eventTimeLabel(event){return eventHasRange(event)&&!event.completed?`${formatDate(event.startsAt)} 至 ${formatDate(event.endsAt)}`:formatDate(eventRecordAt(event))}
function eventFlowDate(event){return eventHasRange(event)&&!event.completed?`${String(event.startsAt||'').slice(0,10)} 至 ${String(event.endsAt||'').slice(0,10)}`:String(eventRecordAt(event)||'').slice(0,10)}
function resolveEvent(event,missed=false){event.completed=true;event.missed=missed;if(eventHasRange(event))event.completedAt=nowText();else delete event.completedAt}
function restoreEvent(event){event.completed=false;event.missed=false;delete event.completedAt}
function bindEventTimeMode(form){const mode=form.elements.timeMode,endField=form.querySelector('[data-end-field]'),endInput=form.elements.endsAt;const sync=()=>{const ranged=mode.value==='range';endField.hidden=!ranged;endInput.required=ranged;if(!ranged)endInput.value=''};mode.onchange=sync;sync()}
function eventFormData(form){const values=Object.fromEntries(new FormData(form));const ranged=values.timeMode==='range';delete values.timeMode;values.startsAt=String(values.startsAt||'').replace('T',' ');if(ranged){values.endsAt=String(values.endsAt||'').replace('T',' ');const start=new Date(values.startsAt.replace(' ','T')).getTime(),end=new Date(values.endsAt.replace(' ','T')).getTime();if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error('结束时间必须晚于开始时间')}else delete values.endsAt;return values}
function badge(v){const kind=STAGES.includes(v)?'badge-stage':(STATUSES.includes(v)?'badge-status':'');return `<span class="badge ${kind} tone-${tones[v]||'gray'}">${esc(v)}</span>`}
const PROGRESS_STALE_DAYS=10;
function appById(id){return state.applications.find(x=>x.id===id)}
function upcoming(){return state.events.filter(e=>!e.completed).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))}
function pendingFollowups(){const now=Date.now();return upcoming().filter(e=>{const t=new Date(String(eventDeadlineAt(e)||'').replace(' ','T')).getTime();return t<now-2*3600e3&&!e.missed})}
function isInterviewEvent(event){return event.type==='面试'||/面试|[一二三四五六七八九]面|HR|电话/i.test(String(event.type||'')+' '+String(event.title||''))}
function progressHealth(a){
  if(['Offer','已结束'].includes(a.stage)||['已通过','未通过','已放弃','已结束'].includes(a.status))return null;
  const related=state.events.filter(e=>e.applicationId===a.id&&isInterviewEvent(e));
  const hasUpcoming=related.some(e=>!e.completed&&!e.missed&&new Date(String(eventDeadlineAt(e)||'').replace(' ','T')).getTime()>=Date.now());
  if(hasUpcoming)return null;
  const completed=related.filter(e=>e.completed&&!e.missed);
  if(!completed.length)return null;
  const reference=Math.max(...completed.map(e=>new Date(String(eventRecordAt(e)||'').replace(' ','T')).getTime()).filter(Number.isFinite));
  if(!Number.isFinite(reference))return null;
  const days=Math.max(0,Math.floor((Date.now()-reference)/86400000));
  if(days<=3)return{label:'进展正常',className:'health-good',days};
  if(days<PROGRESS_STALE_DAYS)return{label:'等待较久',className:'health-watch',days};
  return{label:'建议确认',className:'health-risk',days};
}
function healthBadge(a){const health=progressHealth(a);return health?`<span class="badge badge-health ${health.className}" title="已经 ${health.days} 天没有新进展">${health.label}<b>${health.days}天</b></span>`:''}
function latestProgressTime(a){
  const timelineTimes=(a.timeline||[])
    .filter(item=>!item.eventId&&item.title!=='创建投递记录')
    .map(item=>item.at);
  const completedEventTimes=state.events
    .filter(e=>e.applicationId===a.id&&e.completed&&!e.missed)
    .map(eventRecordAt);
  const times=[a.appliedDate]
    .concat(timelineTimes,completedEventTimes)
    .map(value=>new Date(String(value||'').replace(' ','T')).getTime())
    .filter(Number.isFinite);
  return times.length?Math.max(...times):0;
}
function hasInterviewProgress(a){return ['面试','Offer'].includes(a.stage)||a.status==='已通过'||state.events.some(e=>e.applicationId===a.id&&!e.missed&&(isInterviewEvent(e)||e.type==='Offer'))}
function hasAssessmentOrTestProgress(a){return ['测评','笔试'].includes(a.stage)||state.events.some(e=>e.applicationId===a.id&&!e.missed&&['测评','笔试'].includes(e.type))}
function applicationProgressTier(a){return hasInterviewProgress(a)?0:hasAssessmentOrTestProgress(a)?1:2}
function nextUpcomingTime(a){
  const now=Date.now();
  const times=state.events.filter(e=>e.applicationId===a.id&&!e.completed&&!e.missed).map(e=>{const start=new Date(String(e.startsAt||'').replace(' ','T')).getTime(),end=new Date(String(eventDeadlineAt(e)||'').replace(' ','T')).getTime();return start>=now?start:end>=now?now:NaN}).filter(Number.isFinite);
  return times.length?Math.min(...times):Infinity;
}
function compareApplications(a,b){
  const aRejected=a.status==='未通过',bRejected=b.status==='未通过';
  if(aRejected!==bRejected)return aRejected?1:-1;
  if(aRejected&&bRejected){
    const updated=value=>new Date(String(value.updatedAt||value.createdAt||'').replace(' ','T')).getTime()||0;
    return updated(b)-updated(a);
  }
  const aUpcoming=nextUpcomingTime(a),bUpcoming=nextUpcomingTime(b);
  const aHasUpcoming=Number.isFinite(aUpcoming),bHasUpcoming=Number.isFinite(bUpcoming);
  if(aHasUpcoming!==bHasUpcoming)return aHasUpcoming?-1:1;
  if(aHasUpcoming&&bHasUpcoming&&aUpcoming!==bUpcoming)return aUpcoming-bUpcoming;
  const aTier=applicationProgressTier(a),bTier=applicationProgressTier(b);
  if(aTier!==bTier)return aTier-bTier;
  return latestProgressTime(b)-latestProgressTime(a);
}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}
function fallbackDailyQuote(){const quotes=['今天多走一步，明天就多一个选择。','把注意力放在能推进的下一步上。','每一次认真准备，都在靠近更合适的机会。','慢一点没有关系，只要方向仍在向前。','机会会迟到，但你的积累不会白费。','先完成今天能完成的，再把答案交给时间。','保持行动，好的结果往往在坚持之后出现。'];return quotes[new Date().getDay()]}
function dailyQuoteCache(){try{return JSON.parse(localStorage.getItem(DAILY_QUOTE_KEY)||'null')}catch{return null}}
function showDailyQuote(text,author=''){const holder=document.querySelector('#dailyQuote');if(!holder)return;holder.innerHTML=`<button type="button" class="daily-quote-refresh" onclick="event.stopPropagation();refreshDailyQuote()" title="换一句" aria-label="重新生成每日一句">✦</button><div><small class="daily-quote-label">今日一句</small><p>${esc(text)}${author?`<em>— ${esc(author)}</em>`:''}</p></div><span class="daily-quote-sparks" aria-hidden="true"><b></b><b></b><b></b><b></b><b></b><b></b><b></b></span>`;holder.classList.toggle('hidden',page!=='home')}
function celebrateDailyQuote(){const holder=document.querySelector('#dailyQuote');if(!holder||page!=='home')return;holder.classList.remove('refresh-complete');void holder.offsetWidth;holder.classList.add('refresh-complete');setTimeout(()=>holder.classList.remove('refresh-complete'),900)}
async function generateDailyQuote(force=false){const holder=document.querySelector('#dailyQuote');if(!holder||dailyQuoteRequest)return;const previous=dailyQuoteCache();if(!state.settings.apiUrl||!state.settings.model||!state.settings.apiKey){if(previous?.date===today()&&previous.quote)showDailyQuote(previous.quote,previous.author);else showDailyQuote(fallbackDailyQuote());if(force)toast('请先在设置中完成大模型 API 配置');return}if(previous?.date===today()&&previous.quote)showDailyQuote(previous.quote,previous.author);else holder.innerHTML='<button type="button" class="daily-quote-refresh" disabled aria-label="正在生成每日一句">✦</button><div><small class="daily-quote-label">今日一句</small><p class="daily-quote-loading">正在准备今天的内容…</p></div>';holder.classList.add('is-refreshing');holder.querySelector('.daily-quote-refresh')?.setAttribute('disabled','');dailyQuoteRequest=fetch('/api/daily-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state.settings,date:today()})}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||'生成失败');const value={date:today(),quote:result.quote,author:result.author||''};localStorage.setItem(DAILY_QUOTE_KEY,JSON.stringify(value));showDailyQuote(value.quote,value.author);celebrateDailyQuote()}).catch(error=>{if(previous?.date===today()&&previous.quote)showDailyQuote(previous.quote,previous.author);else showDailyQuote(fallbackDailyQuote());if(force)toast(`换一句失败：${error.message}`,{type:'error',duration:4000})}).finally(()=>{dailyQuoteRequest=null;holder.classList.remove('is-refreshing')});await dailyQuoteRequest}
function refreshDailyQuote(){generateDailyQuote(true)}
async function renderDailyQuote(){const holder=document.querySelector('#dailyQuote');if(!holder)return;holder.classList.toggle('hidden',page!=='home');if(page!=='home')return;const cached=dailyQuoteCache();if(cached?.date===today()&&cached.quote){showDailyQuote(cached.quote,cached.author);return}if(localDataReady)generateDailyQuote()}
const content=document.querySelector('#content');
// 持久连接用于识别页面是否真正关闭；普通刷新会自动重新连接。
const pageSession=new EventSource('/api/session');
const pageMeta={home:['首页','掌握每一次机会的进展'],applications:['投递记录','查看并更新岗位的当前状态'],calendar:['日程',''],mail:['邮件识别','粘贴通知正文，让大模型提取关键信息'],stats:['统计','了解投递转化与当前分布'],settings:['设置','配置大模型及管理本地数据']};
document.querySelector('#nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(b)navigate(b.dataset.page)};
document.querySelector('#quickAdd').onclick=()=>openApplicationForm();
document.querySelector('#modalClose').onclick=closeModal;document.querySelector('#modalMask').onclick=e=>{if(e.target.id==='modalMask')closeModal()};
function navigate(p){page=p;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));document.querySelector('#pageTitle').textContent=pageMeta[p][0];document.querySelector('#pageSubtitle').textContent=pageMeta[p][1];document.querySelector('#quickAdd').classList.toggle('hidden',!['home','applications'].includes(p));content.classList.toggle('home-workbench',p==='home');renderDailyQuote();render()}
function render(){({home:renderHome,applications:renderApplications,calendar:renderCalendar,mail:renderMail,stats:renderStats,settings:renderSettings}[page]||renderHome)()}
function eventLocation(e){if(!e.location)return '';if(/^https?:\/\//i.test(e.location))return ` · <a href="${esc(e.location)}" target="_blank" rel="noreferrer" onclick="event.stopPropagation()">打开链接</a>`;return ` · ${esc(e.location)}`}
function eventTypeTone(value){return({'测评':'assessment','笔试':'test','面试':'interview','Offer':'offer','其他':'other'})[value]||'other'}
function eventCard(e){const deadline=new Date(String(eventDeadlineAt(e)||'').replace(' ','T')),past=deadline<new Date(),timeLabel=eventTimeLabel(e),isRange=eventHasRange(e)&&!e.completed,first=isRange?formatDate(e.startsAt).split(' ')[0]:timeLabel.split(' ')[0],rest=isRange?timeLabel:timeLabel.slice(first.length).trim();return `<div class="event-card event-type-${eventTypeTone(e.type)} ${isRange?'event-card-range':''} ${e.completed?'done':''} ${past&&!e.completed?'overdue':''}" data-event-id="${esc(e.id)}" data-starts-at="${esc(eventRecordAt(e)||'')}"><div class="event-time">${esc(first)}<small>${esc(rest)}</small></div><div><div class="event-title">${esc(e.company)} · ${esc(e.title||e.type)}</div><div class="event-sub">${esc(e.position)}${eventLocation(e)} ${badge(e.missed?'已错过':(e.result||e.type))}</div><div class="event-sub event-note ${e.notes?'':'empty-note'}"><b>备注：</b>${esc(e.notes||'暂无备注')}</div></div><div class="event-card-actions"><button class="ghost" onclick="editSchedule('${e.id}')">编辑</button><button class="ghost delete-schedule" onclick="deleteSchedule('${e.id}')">删除</button>${e.completed?'<span class="event-done-mark">✓</span>':`<button class="secondary" onclick="completeEvent('${e.id}')">完成</button>`}</div></div>`}
function renderHome(){const events=upcoming(),follow=pendingFollowups();content.innerHTML=`${follow.length?`<div class="checkin home-overdue-alert" role="status"><div class="checkin-icon" aria-hidden="true">!</div><div class="checkin-copy"><span>日程超时提醒</span><strong>${follow.length} 项日程已到期超过 2 小时</strong><p>最近一项：${esc(follow[0].company)} · ${esc(follow[0].title||follow[0].type)}，请及时标记完成或错过。</p></div><button class="checkin-action" onclick="navigate('calendar')">立即处理 →</button></div>`:''}<div class="grid two-col"><div class="panel"><div class="panel-head"><h2>最近投递</h2><button class="link-btn" onclick="navigate('applications')">查看全部</button></div><div class="cards">${state.applications.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5).map(a=>appCard(a)).join('')||'<div class="empty">还没有投递记录，点击右上角开始添加</div>'}</div></div><div class="panel"><div class="panel-head"><h2>近期日程</h2><button class="link-btn" onclick="navigate('calendar')">查看全部</button></div><div class="cards">${events.slice(0,4).map(eventCard).join('')||'<div class="empty">暂无待完成日程</div>'}</div></div></div>`}
function applicationFlowNodes(a){
  const events=state.events.filter(e=>e.applicationId===a.id).sort((x,y)=>String(eventRecordAt(x)).localeCompare(String(eventRecordAt(y))));
  const visual=(label,type='')=>{const text=`${type} ${label}`;if(text.includes('未通过')||text.includes('错过')||text.includes('放弃'))return['failed','×'];if(text.includes('Offer')||text.includes('录用')||text.includes('通过'))return['offer','★'];if(text.includes('测评'))return['assessment','◇'];if(text.includes('笔试'))return['test','✎'];if(text.includes('面试')||/[一二三四五六七八九]面/.test(text)||text.includes('HR'))return['interview','◎'];if(text.includes('电话'))return['phone','☎'];if(text.includes('等待'))return['waiting','◷'];if(text.includes('投递'))return['applied','↗'];return['other','＋'];};
  const [appliedStyle,appliedIcon]=visual('已投递');
  const nodes=[{label:'已投递',date:a.appliedDate||'',kind:events.length||a.stage!=='已投递'?'done':'current',style:appliedStyle,icon:appliedIcon}];
  events.forEach(e=>{const eventTime=new Date(String(eventDeadlineAt(e)||'').replace(' ','T')).getTime(),kind=e.missed?'failed':e.completed?'done':eventTime>Date.now()?'upcoming':'current',[style,icon]=visual(e.title||e.type,e.type);nodes.push({label:e.title||e.type,date:eventFlowDate(e),kind,style,icon});});
  const last=nodes[nodes.length-1],latestEvent=events[events.length-1],latestEventPending=latestEvent&&!latestEvent.completed&&!latestEvent.missed,terminal=a.status==='未通过'||a.status==='已放弃'||a.status==='已结束',offer=a.stage==='Offer'||a.status==='已通过',enteredInterview=a.stage==='面试'||events.some(isInterviewEvent);
  let statusLabel=offer?'Offer':terminal?a.status:a.status;
  if(statusLabel==='等待结果'&&!enteredInterview)statusLabel='';
  if(statusLabel&&statusLabel!==last.label&&!(statusLabel==='等待结果'&&latestEventPending)){const [style,icon]=visual(statusLabel);nodes.push({label:statusLabel,date:offer?'':'当前状态',kind:offer?'success':terminal?'failed':'current',style,icon});}
  else if(!events.length&&a.stage!=='已投递'){const [style,icon]=visual(a.stage,a.stage);nodes.push({label:a.stage,date:'当前阶段',kind:'current',style,icon});}
  return nodes;
}
function applicationFlow(a,slots=0){const nodes=applicationFlowNodes(a),columnCount=Math.max(slots,nodes.length,1);return `<div class="application-flow" style="--flow-slots:${columnCount}" aria-label="投递流程">${nodes.map(node=>`<div class="flow-node ${node.kind} flow-${node.style}"><i>${node.icon}</i><b>${esc(node.label)}</b><small>${esc(node.date)}</small></div>`).join('')}</div>`}
function applicationCardCategory(a){
  if(a.stage==='Offer'||a.status==='已通过')return'offer';
  if(a.stage==='已结束'||['未通过','已放弃','已结束'].includes(a.status))return'stopped';
  if(Number.isFinite(nextUpcomingTime(a)))return'pending';
  if(hasInterviewProgress(a))return'interview';
  if(hasAssessmentOrTestProgress(a))return'assessment';
  return'applied';
}
function appCard(a,flowSlots=0){const category=applicationCardCategory(a);return `<div class="application-card application-card-flow application-card-${category}" onclick="openDetail('${a.id}')"><div class="card-overview"><div class="card-summary-line"><strong title="${esc(a.company)}">${esc(a.company)}</strong><i>·</i><span class="card-position" title="${esc(a.position)}">${esc(a.position)}</span><i>·</i><span>${esc(a.city||'地点未填')}</span><i>·</i><span>${esc(a.channel||'渠道未填')}</span></div><div class="card-health">${healthBadge(a)}</div></div>${applicationFlow(a,flowSlots)}</div>`}
function applicationHeatmapBounds(){const current=new Date(new Date().getFullYear(),new Date().getMonth(),1),dates=state.applications.map(a=>String(a.appliedDate||'')).filter(value=>/^\d{4}-\d{2}-\d{2}$/.test(value)).sort(),earliest=dates.length?new Date(Number(dates[0].slice(0,4)),Number(dates[0].slice(5,7))-1,1):current,latest=dates.length?new Date(Number(dates[dates.length-1].slice(0,4)),Number(dates[dates.length-1].slice(5,7))-1,1):current;return {earliest,latest}}
function changeApplicationHeatmapMonth(offset){const {earliest,latest}=applicationHeatmapBounds(),candidate=new Date(applicationHeatmapMonth.getFullYear(),applicationHeatmapMonth.getMonth()+offset,1);applicationHeatmapMonth=candidate<earliest?earliest:candidate>latest?latest:candidate;renderApplications()}
function applicationMonthHeatmap(){const {earliest,latest}=applicationHeatmapBounds();if(applicationHeatmapMonth<earliest)applicationHeatmapMonth=earliest;if(applicationHeatmapMonth>latest)applicationHeatmapMonth=latest;const year=applicationHeatmapMonth.getFullYear(),month=applicationHeatmapMonth.getMonth(),prefix=`${year}-${String(month+1).padStart(2,'0')}`,counts={};state.applications.forEach(a=>{if(String(a.appliedDate||'').startsWith(prefix))counts[a.appliedDate]=(counts[a.appliedDate]||0)+1});const max=Math.max(1,...Object.values(counts)),offset=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=[];for(let index=0;index<42;index++){const day=index-offset+1;if(day<1||day>days){cells.push('<i class="outside"></i>');continue}const key=`${prefix}-${String(day).padStart(2,'0')}`,count=counts[key]||0,level=count?Math.max(1,Math.ceil(count/max*4)):0;cells.push(`<i class="heat-${level}" title="${key}：投递 ${count} 个岗位"></i>`)}const total=Object.values(counts).reduce((sum,value)=>sum+value,0),atEarliest=applicationHeatmapMonth.getTime()===earliest.getTime(),atLatest=applicationHeatmapMonth.getTime()===latest.getTime();return `<div class="application-heatmap"><div class="heatmap-summary"><b>${year}年${month+1}月</b><span>共 ${total} 个岗位</span><div class="heatmap-scale"><i></i><i></i><i></i><i></i><i></i></div></div><div class="heatmap-grid" aria-label="${year}年${month+1}月每日投递分布">${cells.join('')}</div><div class="heatmap-month-switch" aria-label="切换投递分布月份"><button type="button" onclick="event.stopPropagation();changeApplicationHeatmapMonth(-1)" title="${atEarliest?'已经是最早投递月份':'上个月'}" ${atEarliest?'disabled':''}>‹</button><b>${month+1}月</b><button type="button" onclick="event.stopPropagation();changeApplicationHeatmapMonth(1)" title="${atLatest?'已经是最晚投递月份':'下个月'}" ${atLatest?'disabled':''}>›</button></div></div>`}
function renderApplications(){content.innerHTML=`<div class="application-tools"><input class="search application-search-input" id="search" placeholder="搜索公司或岗位"><select class="search application-status-filter" id="statusFilter"><option value="">全部状态</option>${STATUSES.map(x=>`<option>${x}</option>`).join('')}</select>${applicationMonthHeatmap()}</div><div class="application-color-legend" aria-label="投递卡片颜色说明"><span class="legend-title">卡片颜色</span><span class="legend-item legend-pending"><i></i>待参加日程</span><span class="legend-item legend-interview"><i></i>有面试进展</span><span class="legend-item legend-assessment"><i></i>测评 / 笔试</span><span class="legend-item legend-applied"><i></i>仅投递</span><span class="legend-item legend-stopped"><i></i>未通过 / 已结束</span><span class="legend-item legend-offer"><i></i>Offer / 已通过</span></div><div class="cards" id="applicationList"></div>`;const refresh=()=>{const q=document.querySelector('#search').value.trim().toLowerCase(),s=document.querySelector('#statusFilter').value;const items=state.applications.filter(a=>(!q||(a.company+a.position).toLowerCase().includes(q))&&(!s||a.status===s)).sort(compareApplications),flowSlots=Math.max(1,...items.map(a=>applicationFlowNodes(a).length));document.querySelector('#applicationList').innerHTML=items.map(a=>appCard(a,flowSlots)).join('')||'<div class="panel empty">没有符合条件的投递记录</div>'};document.querySelector('#search').oninput=refresh;document.querySelector('#statusFilter').onchange=refresh;refresh()}
function renderCalendar(){const events=state.events.slice().sort((a,b)=>String(eventRecordAt(a)).localeCompare(String(eventRecordAt(b)))),todo=events.filter(e=>!e.completed),done=events.filter(e=>e.completed);content.innerHTML=`<div class="panel-head"><div></div><button class="primary" onclick="openEventForm()">＋ 新增日程</button></div><div class="panel"><div class="panel-head"><h2>待完成 · ${todo.length}</h2></div><div class="cards">${todo.map(e=>eventCard(e)+(pendingFollowups().some(x=>x.id===e.id)?`<div class="form-actions"><button class="success" onclick="completeEvent('${e.id}')">已经完成</button><button class="danger" onclick="missEvent('${e.id}')">已经错过</button></div>`:'')).join('')||'<div class="empty">暂无待完成日程</div>'}</div></div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>已完成 / 已错过</h2></div><div class="cards">${done.map(eventCard).join('')||'<div class="empty">暂无历史日程</div>'}</div></div>`}
function openModal(title,html){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modalMask').classList.remove('hidden')}
function closeModal(){document.querySelector('#modalMask').classList.add('hidden')}
function options(arr,value){return arr.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}
function openApplicationForm(idValue='',prefill={}){const a=idValue?appById(idValue):{company:'',position:'',city:'',channel:'官网',appliedDate:today(),stage:'已投递',status:'等待结果',notes:'',...prefill};openModal(idValue?'编辑投递':'新建投递',`<form id="appForm" class="form-grid"><div class="field"><label>公司名称 *</label><input name="company" required value="${esc(a.company)}"></div><div class="field"><label>岗位名称 *</label><input name="position" required value="${esc(a.position)}"></div><div class="field"><label>工作地点</label><input name="city" value="${esc(a.city)}"></div><div class="field"><label>投递渠道</label><select name="channel">${options(CHANNELS,a.channel)}</select></div><div class="field"><label>投递日期</label><input type="date" name="appliedDate" value="${esc(a.appliedDate)}"></div><div class="field"><label>当前阶段</label><select name="stage">${options(STAGES,a.stage)}</select></div><div class="field"><label>当前状态</label><select name="status">${options(STATUSES,a.status)}</select></div><div class="field full"><label>备注</label><textarea name="notes" placeholder="岗位编号、联系人或其他简短信息">${esc(a.notes)}</textarea></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">取消</button><button class="primary">保存</button></div></form>`);document.querySelector('#appForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const old=idValue?appById(idValue):null;const at=nowText(),timeline=old?.timeline||[];if(!old)timeline.unshift({id:id('tl'),at,title:'创建投递记录'});else if(old.stage!==data.stage||old.status!==data.status)timeline.unshift({id:id('tl'),at,title:`更新为 ${data.stage} · ${data.status}`});const record={...old,...data,id:idValue||id('app'),timeline,createdAt:old?.createdAt||at,updatedAt:at};if(old)state.applications=state.applications.map(x=>x.id===idValue?record:x);else state.applications.unshift(record);save();closeModal();render();toast('投递记录已保存')}}
function openDetail(idValue){const a=appById(idValue);if(!a)return;selectedId=idValue;const events=state.events.filter(e=>e.applicationId===idValue).sort((x,y)=>String(eventRecordAt(y)).localeCompare(String(eventRecordAt(x))));openModal('投递详情',`<div class="detail-head"><div><h3>${esc(a.company)}</h3><div>${esc(a.position)} · ${esc(a.city||'地点未填')}</div></div><div>${badge(a.stage)} ${badge(a.status)}</div></div><div class="detail-actions"><button class="secondary" onclick="openApplicationForm('${a.id}')">编辑信息 / 状态</button><button class="primary" onclick="openEventForm('${a.id}')">追加安排</button><button class="success" onclick="quickStatus('${a.id}','offer')">收到 Offer</button><button class="danger" onclick="quickStatus('${a.id}','reject')">未通过</button><button class="ghost" onclick="removeApplication('${a.id}')">删除</button></div><div class="section-label">基本信息</div><div class="settings-note">投递日期：${esc(a.appliedDate||'未填写')}　投递渠道：${esc(a.channel||'未填写')}<br>备注：${esc(a.notes||'无')}</div><div class="section-label">安排记录</div><div class="cards">${events.map(eventCard).join('')||'<div class="empty">还没有笔试或面试安排</div>'}</div><div class="section-label">状态历史</div><div class="timeline">${(a.timeline||[]).map(t=>`<div class="timeline-item"><b>${esc(t.title)}</b><br><small>${esc(t.at)}</small></div>`).join('')||'<div class="empty">暂无历史</div>'}</div>`)}
function quickStatus(idValue,type){const a=appById(idValue),at=nowText();if(type==='offer'){a.stage='Offer';a.status='已通过';a.timeline.unshift({id:id('tl'),at,title:'更新为 Offer · 已通过'})}else{a.stage='已结束';a.status='未通过';a.timeline.unshift({id:id('tl'),at,title:'更新为 已结束 · 未通过'})}a.updatedAt=at;save();closeModal();render();toast('岗位状态已更新')}
function removeApplication(idValue){const application=appById(idValue);if(!application)return;confirmAction('删除投递记录',`将删除“${application.company} · ${application.position}”及其全部日程。删除后仍可在提示中撤销。`,()=>{createUndoSnapshot('投递记录');state.applications=state.applications.filter(a=>a.id!==idValue);state.events=state.events.filter(e=>e.applicationId!==idValue);save();closeModal();render();toast('投递记录已删除',{type:'warning',action:'撤销',onAction:undoLastChange,duration:8000})},{danger:true})}
function openEventForm(appId=''){if(!state.applications.length){toast('请先新建一条投递记录');return}const a=appById(appId)||state.applications[0];openModal('新增日程',`<form id="eventForm" class="form-grid"><div class="field full"><label>关联岗位</label><select name="applicationId">${state.applications.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${esc(x.company)} · ${esc(x.position)}</option>`).join('')}</select></div><div class="field"><label>类型</label><select name="type">${options(TYPES,'面试')}</select></div><div class="field"><label>安排名称</label><input name="title" placeholder="如：一面、在线笔试" required></div><div class="field"><label>时间类型</label><select name="timeMode"><option value="point">时间点</option><option value="range">时间段</option></select></div><div class="field"><label>开始时间</label><input type="datetime-local" name="startsAt" required></div><div class="field" data-end-field hidden><label>结束时间</label><input type="datetime-local" name="endsAt"></div><div class="field"><label>地点 / 会议方式</label><input name="location" placeholder="如：线上、腾讯会议"></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">取消</button><button class="primary">保存安排</button></div></form>`);const form=document.querySelector('#eventForm');bindEventTimeMode(form);form.onsubmit=e=>{e.preventDefault();try{const d=eventFormData(e.target),app=appById(d.applicationId),eventId=id('evt'),createdAt=nowText();state.events.push({...d,id:eventId,company:app.company,position:app.position,completed:false,missed:false,createdAt});if(['测评','笔试','面试','Offer'].includes(d.type)){app.stage=d.type;app.status=d.type==='Offer'?'已通过':'等待结果';app.timeline.unshift({id:id('tl'),eventId,at:createdAt,title:`新增${d.type}安排：${d.title}`});app.updatedAt=createdAt}save();closeModal();render();toast('日程已添加')}catch(error){toast(error.message,{type:'error'})}}}
function completeEvent(idValue){const e=state.events.find(x=>x.id===idValue);if(e){resolveEvent(e);save();closeModal();render();toast('已标记完成')}}
function missEvent(idValue){const e=state.events.find(x=>x.id===idValue);if(e){resolveEvent(e,true);save();render();toast('已标记错过')}}
function renderMail(){content.innerHTML=`<div class="grid mail-layout"><div class="panel mail-box"><div class="panel-head"><h2>邮件正文</h2><button class="link-btn" onclick="document.querySelector('#mailBody').value=''">清空</button></div><textarea id="mailBody" class="search" placeholder="将完整的笔试、面试或 Offer 通知正文粘贴到这里……"></textarea><div class="form-actions"><button class="primary" id="recognizeBtn">✦ 使用大模型识别</button></div></div><div class="panel"><div class="panel-head"><h2>识别结果</h2></div><div id="recognition" class="recognition">${mailResult?mailResultHtml():`<div class="empty">识别出的公司、岗位、时间等信息会显示在这里，未识别内容可手动补充。</div>`}</div></div></div>`;document.querySelector('#recognizeBtn').onclick=recognizeMail}
function mailResultHtml(){const r=mailResult;return `<div class="field"><label>公司</label><input id="mrCompany" value="${esc(r.company)}"></div><div class="field"><label>岗位</label><input id="mrPosition" value="${esc(r.position)}"></div><div class="field"><label>通知类型</label><select id="mrType">${options(TYPES,r.noticeType)}</select></div><div class="field"><label>时间</label><input id="mrStarts" value="${esc(r.startsAt)}" placeholder="YYYY-MM-DD HH:mm"></div><div class="field"><label>面试地点 / 视频链接</label><input id="mrLocation" value="${esc(r.location)}" placeholder="视频会议链接或线下面试地址"></div><div class="field"><label>备注</label><textarea id="mrSummary" placeholder="如有需要，可在这里手动填写"></textarea></div><div class="form-actions"><button class="primary" onclick="useMailResult()">使用识别结果</button></div>`}
async function recognizeMail(){const body=document.querySelector('#mailBody').value.trim(),btn=document.querySelector('#recognizeBtn');if(!body)return toast('请先粘贴邮件正文');btn.style.width=`${Math.ceil(btn.getBoundingClientRect().width)}px`;btn.disabled=true;btn.textContent='正在识别…';try{const res=await fetch('/api/recognize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state.settings,body})}),data=await res.json();if(!res.ok)throw new Error(data.error||'识别失败');mailResult=data;document.querySelector('#recognition').innerHTML=mailResultHtml();toast('识别完成')}catch(e){toast('识别失败：'+e.message,{type:'error',duration:5000})}finally{btn.disabled=false;btn.textContent='✦ 使用大模型识别';btn.style.width=''}}
function useMailResult(){const r={company:document.querySelector('#mrCompany').value,position:document.querySelector('#mrPosition').value,stage:mailResult.suggestedStage||'已投递',status:STATUSES.includes(mailResult.suggestedStatus)?mailResult.suggestedStatus:'等待结果',notes:document.querySelector('#mrSummary').value};closeModal();openApplicationForm('',r)}
function renderStats(){const byStage=STAGES.map(s=>[s,state.applications.filter(a=>a.stage===s).length]),max=Math.max(1,...byStage.map(x=>x[1]));content.innerHTML=`<div class="grid stats-grid"><div class="stat-card"><small>投递总数</small><strong>${state.applications.length}</strong></div><div class="stat-card"><small>面试阶段</small><strong>${state.applications.filter(a=>a.stage==='面试').length}</strong></div><div class="stat-card"><small>Offer</small><strong>${state.applications.filter(a=>a.stage==='Offer').length}</strong></div><div class="stat-card"><small>结束 / 未通过</small><strong>${state.applications.filter(a=>['已结束','未通过'].includes(a.status)).length}</strong></div></div><div class="grid two-col"><div class="panel"><h2>阶段分布</h2>${byStage.map(([s,n])=>`<div class="chart-row"><span>${s}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join('')}</div><div class="panel"><h2>渠道分布</h2>${Object.entries(state.applications.reduce((m,a)=>(m[a.channel||'未填写']=(m[a.channel||'未填写']||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).map(([s,n])=>`<div class="chart-row"><span>${esc(s)}</span><div class="bar"><i style="width:${n/Math.max(1,state.applications.length)*100}%"></i></div><b>${n}</b></div>`).join('')||'<div class="empty">暂无数据</div>'}</div></div>`}
function renderSettings(){const s=state.settings;content.innerHTML=`<div class="grid two-col"><div class="panel"><h2>大模型 API</h2><p class="settings-note">支持 OpenAI 兼容接口。可填写服务根地址、以 /v1 结尾的地址，或完整的 /chat/completions 地址。API Key 仅保存在本机浏览器中。</p><form id="settingsForm" class="form-grid"><div class="field full"><label>API 地址</label><input name="apiUrl" value="${esc(s.apiUrl)}"></div><div class="field"><label>模型名称</label><input name="model" value="${esc(s.model)}"></div><div class="field"><label>API Key</label><input type="password" name="apiKey" value="${esc(s.apiKey)}"></div><div class="form-actions"><button class="primary">保存配置</button></div></form></div><div class="panel"><h2>数据管理</h2><p class="settings-note">建议定期导出数据。导入会替换当前投递和日程，请妥善保管导出的 JSON 文件。</p><div class="detail-actions"><button class="secondary" onclick="exportData()">导出数据</button><label class="ghost" style="cursor:pointer">导入数据<input type="file" accept=".json" hidden onchange="importData(this)"></label></div></div></div>`;document.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();state.settings=Object.fromEntries(new FormData(e.target));save();toast('API 配置已保存')}}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`求职进度本备份_${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(input){const f=input.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.applications)||!Array.isArray(data.events))throw new Error('备份格式不正确');confirmAction('导入备份',`将用备份中的 ${data.applications.length} 条投递和 ${data.events.length} 项日程替换当前数据。`,()=>{state={...initial(),...data};save();render();toast('备份已恢复')})}catch(e){toast(e.message,{type:'error'})}};reader.readAsText(f)}
function clearData(){confirmAction('清空全部数据','将清空所有投递和日程，建议操作前确认自动备份可用。',()=>{state.applications=[];state.events=[];save();render();toast('数据已清空')},{danger:true})}
Object.assign(window,{navigate,openApplicationForm,openDetail,openEventForm,closeModal,quickStatus,removeApplication,completeEvent,missEvent,useMailResult,exportData,importData,clearData});
render();
loadFromLocalFile().finally(()=>{localDataReady=true;renderDailyQuote()});
const TIME_SENSITIVE_REFRESH_MS=60*1000;
function refreshTimeSensitiveView(){
  const modalClosed=document.querySelector('#modalMask')?.classList.contains('hidden');
  if(document.visibilityState==='visible'&&modalClosed&&['home','calendar'].includes(page))render();
}
setInterval(refreshTimeSensitiveView,TIME_SENSITIVE_REFRESH_MS);
window.addEventListener('focus',refreshTimeSensitiveView);
document.addEventListener('visibilitychange',refreshTimeSensitiveView);
