<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'

export type SelectOption = { value: string; label: string; group?: string; disabled?: boolean }
const props = withDefaults(defineProps<{ modelValue:string; options:SelectOption[]|string[]; disabled?:boolean; placeholder?:string; align?:'left'|'center' }>(), { disabled:false, placeholder:'请选择', align:'left' })
const emit = defineEmits<{ 'update:modelValue':[value:string] }>()
const root=ref<HTMLElement|null>(null), trigger=ref<HTMLButtonElement|null>(null), open=ref(false), activeIndex=ref(-1)
const normalized=computed<SelectOption[]>(()=>props.options.map(item=>typeof item==='string'?{value:item,label:item}:item))
const selected=computed(()=>normalized.value.find(item=>item.value===props.modelValue))
function close(){open.value=false;activeIndex.value=-1}
function toggle(){if(props.disabled)return;open.value=!open.value;activeIndex.value=open.value?Math.max(0,normalized.value.findIndex(item=>item.value===props.modelValue)):-1}
function choose(item:SelectOption){if(item.disabled)return;emit('update:modelValue',item.value);close();nextTick(()=>trigger.value?.focus())}
function move(offset:number){if(!open.value){toggle();return}if(!normalized.value.length)return;let index=activeIndex.value;do index=(index+offset+normalized.value.length)%normalized.value.length;while(normalized.value[index]?.disabled);activeIndex.value=index;nextTick(()=>root.value?.querySelector<HTMLElement>(`[data-index="${index}"]`)?.scrollIntoView({block:'nearest'}))}
function onKeydown(event:KeyboardEvent){if(event.key==='ArrowDown'){event.preventDefault();move(1)}else if(event.key==='ArrowUp'){event.preventDefault();move(-1)}else if(event.key==='Enter'||event.key===' '){event.preventDefault();open.value&&activeIndex.value>=0?choose(normalized.value[activeIndex.value]):toggle()}else if(event.key==='Escape'){event.preventDefault();close();trigger.value?.focus()}}
function onDocumentClick(event:MouseEvent){if(!root.value?.contains(event.target as Node))close()}
onMounted(()=>document.addEventListener('pointerdown',onDocumentClick));onBeforeUnmount(()=>document.removeEventListener('pointerdown',onDocumentClick))
</script>
<template><div ref="root" :class="['base-select',`align-${align}`,{open,disabled}]" @keydown="onKeydown"><button ref="trigger" type="button" class="select-trigger" :disabled="disabled" :aria-expanded="open" aria-haspopup="listbox" @click="toggle"><span :class="{placeholder:!selected}">{{selected?.label||placeholder}}</span><i aria-hidden="true"></i></button><div v-if="open" class="select-menu" role="listbox"><template v-for="(item,index) in normalized" :key="`${item.group||''}:${item.value}`"><div v-if="item.group&&item.group!==normalized[index-1]?.group" class="select-group">{{item.group}}</div><button type="button" role="option" :data-index="index" :aria-selected="item.value===modelValue" :class="['select-option',{selected:item.value===modelValue,active:index===activeIndex}]" :disabled="item.disabled" @mouseenter="activeIndex=index" @click="choose(item)"><span>{{item.label}}</span><b v-if="item.value===modelValue">✓</b></button></template></div></div></template>
<style scoped>
.base-select{position:relative;width:100%;min-width:0;color:#25324a;font:inherit}.select-trigger{display:flex;width:100%;height:42px;align-items:center;justify-content:space-between;gap:12px;padding:0 14px;border:1px solid #cfd8e6;border-radius:10px;outline:none;color:inherit;background:#fff;font:inherit;font-weight:600;text-align:left;box-shadow:0 1px 2px rgba(31,48,78,.04);transition:border-color .16s ease,box-shadow .16s ease,background .16s ease}.select-trigger:hover{border-color:#9eacc1;background:#fbfcff}.select-trigger:focus-visible,.open .select-trigger{border-color:var(--accent,#4461d8);box-shadow:0 0 0 3px color-mix(in srgb,var(--accent,#4461d8) 16%,transparent)}.select-trigger span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.select-trigger .placeholder{color:#8b96a8;font-weight:500}.select-trigger i{width:8px;height:8px;flex:0 0 8px;border-right:2px solid #65728a;border-bottom:2px solid #65728a;transform:translateY(-2px) rotate(45deg);transition:transform .16s ease}.open .select-trigger i{transform:translateY(2px) rotate(225deg)}.select-menu{position:absolute;top:calc(100% + 7px);right:0;left:0;z-index:90;max-height:min(330px,45vh);overflow:auto;padding:6px;border:1px solid #d9e1ec;border-radius:12px;background:#fff;box-shadow:0 14px 38px rgba(31,42,68,.16),0 3px 10px rgba(31,42,68,.08);scrollbar-width:thin}.select-option{display:flex;width:100%;min-height:38px;align-items:center;justify-content:space-between;gap:12px;padding:8px 10px;border-radius:8px;color:#344054;background:transparent;font:inherit;font-weight:500;text-align:left}.select-option:hover,.select-option.active{color:var(--accent,#4461d8);background:color-mix(in srgb,var(--accent,#4461d8) 9%,white)}.select-option.selected{color:var(--accent,#4461d8);background:color-mix(in srgb,var(--accent,#4461d8) 13%,white);font-weight:700}.select-option b{color:var(--accent,#4461d8)}.select-group{padding:10px 10px 5px;color:#8a94a6;font-size:11px;font-weight:800;letter-spacing:.06em}.align-center .select-trigger,.align-center .select-option{text-align:center}.align-center .select-trigger span,.align-center .select-option span{flex:1}.disabled{opacity:.68}.disabled .select-trigger{cursor:not-allowed;background:#f4f6f9}
</style>
