<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api, apiCached } from './api'
type ConfigView={apiUrl:string;model:string;hasApiKey:boolean;lastFour:string}
const themes=[{id:'blue',name:'海军蓝',note:'理性清爽'},{id:'purple',name:'暮紫',note:'沉稳柔和'},{id:'orange',name:'暖橙',note:'温暖醒目'},{id:'green',name:'森林绿',note:'自然克制'}]
const theme=ref(localStorage.getItem('job-tracker-theme')||'blue')
const config=ref<ConfigView|null>(null)
const form=reactive({apiUrl:'https://api.deepseek.com',model:'deepseek-chat',apiKey:'',clearApiKey:false})
const loading=ref(false),message=ref(''),error=ref('')
onMounted(async()=>{applyTheme(theme.value,false);await loadConfig()})
function applyTheme(value:string,persist=true){const next=themes.some(item=>item.id===value)?value:'blue';theme.value=next;document.documentElement.dataset.theme=next;if(persist){localStorage.setItem('job-tracker-theme',next);message.value='主题已切换为'+themes.find(item=>item.id===next)?.name}}
async function loadConfig(){try{config.value=await apiCached<ConfigView>('/api/poc/ai-sandbox/config');Object.assign(form,{apiUrl:config.value.apiUrl,model:config.value.model,apiKey:'',clearApiKey:false})}catch(cause){error.value=cause instanceof Error?cause.message:'读取 AI 配置失败'}}
async function saveConfig(){loading.value=true;message.value='';error.value='';try{config.value=await api<ConfigView>('/api/poc/ai-sandbox/config',{method:'POST',body:JSON.stringify(form)});form.apiKey='';form.clearApiKey=false;message.value='大模型 API 配置已保存'}catch(cause){error.value=cause instanceof Error?cause.message:'保存 AI 配置失败'}finally{loading.value=false}}
</script>
<template>
<section class="card preference-card"><div class="section-head"><div><span>外观</span><h2>整体色调</h2></div><i title="岗位状态的语义颜色不会随主题改变">ⓘ</i></div><p>选择后立即应用到导航、按钮和主要强调区域。</p><div class="theme-options"><button v-for="item in themes" :key="item.id" type="button" :class="{active:theme===item.id}" @click="applyTheme(item.id)"><i :class="['swatch',item.id]"></i><span><b>{{item.name}}</b><small>{{item.note}}</small></span></button></div></section>
<section class="card preference-card"><div class="section-head"><div><span>智能能力</span><h2>大模型 API</h2></div><i title="用于邮件识别、投递信息规范化和每日一句">ⓘ</i></div><p>支持 OpenAI 兼容接口。API Key 经加密后保存在服务器中，保存后不再显示完整内容。</p><form class="api-form" @submit.prevent="saveConfig"><label class="wide"><span>API 地址</span><input v-model="form.apiUrl" type="url" maxlength="2048" required /></label><label><span>模型名称</span><input v-model="form.model" maxlength="200" required /></label><label><span>API Key {{config?.hasApiKey?'（已配置，末四位 '+config.lastFour+'）':''}}</span><input v-model="form.apiKey" type="password" autocomplete="off" placeholder="留空则保留现有密钥" /></label><label v-if="config?.hasApiKey" class="check wide"><input v-model="form.clearApiKey" type="checkbox" /><span>清除现有 API Key</span></label><button :disabled="loading">{{loading?'保存中…':'保存配置'}}</button></form><p v-if="message" class="success">{{message}}</p><p v-if="error" class="danger">{{error}}</p></section>
<section class="card about-card"><div class="about-brand"><img src="/favicon.svg" alt="" /><div><h2>求职进度本</h2><p>私密、专注、可同步的求职管理工具</p></div></div><dl><div><dt>数据位置</dt><dd>云端数据库，按账号隔离</dd></div><div><dt>API 配置</dt><dd>服务端加密存储</dd></div><div><dt>项目主页</dt><dd><a href="https://github.com/dfaskl/job-tracker-desktop" target="_blank" rel="noreferrer">GitHub ↗</a></dd></div></dl></section>
</template>
<style scoped>
.preference-card,.about-card{display:grid;gap:16px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.section-head h2{margin:4px 0 0}.section-head span{color:var(--accent,#4461d8);font-size:11px;font-weight:800;letter-spacing:.1em}.section-head>i{color:#758198;font-style:normal}.preference-card>p{margin:0}.theme-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.theme-options button{position:relative;display:flex;align-items:center;gap:10px;padding:12px;border:1px solid #dde3ed;color:#344054;background:#fbfcfe;text-align:left}.theme-options button.active{border-color:var(--accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 12%,transparent)}.theme-options button.active::after{content:"✓";position:absolute;top:7px;right:9px;color:var(--accent)}.swatch{width:34px;height:34px;flex:0 0 34px;border-radius:9px}.swatch.blue{background:linear-gradient(135deg,#17233e 50%,#567fce 50%)}.swatch.purple{background:linear-gradient(135deg,#2c203c 50%,#8962bd 50%)}.swatch.orange{background:linear-gradient(135deg,#3a271c 50%,#bd7541 50%)}.swatch.green{background:linear-gradient(135deg,#102c20 50%,#3b9b6c 50%)}.theme-options span{display:grid;gap:2px}.theme-options small{color:#667085}.api-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.api-form label{display:grid;gap:7px;color:#475467;font-size:13px;font-weight:700}.api-form .wide{grid-column:1/-1}.api-form .check{display:flex;align-items:center}.check input{flex:none;width:18px}.api-form button{justify-self:start}.about-brand{display:flex;align-items:center;gap:12px}.about-brand img{width:42px;height:42px}.about-brand h2,.about-brand p{margin:0}.about-card dl{margin:0}.about-card a{color:var(--accent);text-decoration:none}@media(max-width:560px){.theme-options,.api-form{grid-template-columns:1fr}.api-form .wide{grid-column:auto}}
</style>