<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'

const emit = defineEmits<{ navigate: [page: 'home'] }>()
type Slide = { key: string; section: string; title: string; description: string; tip: string; visual: 'home' | 'applications' | 'calendar' | 'mail' | 'stats' | 'interview' | 'team' }
const slides: Slide[] = [
  { key: 'home', section: '从首页开始', title: '先看主页，掌握求职节奏', description: '主页把最近的面试安排、待处理事项和求职动态放在一起。登录后先扫一眼今天和接下来几天的安排，重要节点就不容易漏掉。', tip: '建议先添加正在跟进的岗位，再把已经确定的面试时间记入日程。', visual: 'home' },
  { key: 'applications', section: '管理机会', title: '每个岗位一条进度时间线', description: '在「投递记录」中维护公司、岗位、渠道和当前招聘阶段。收到进展后更新状态，系统会把关键变化串成时间线，方便回看每个机会走到了哪一步。', tip: '可用备注补充联系人、薪资沟通和下一步待办等信息。', visual: 'applications' },
  { key: 'calendar', section: '安排时间', title: '把面试和待办排进日程', description: '日程支持时间点和时间段两种安排，也可以记录面试轮次、地点或会议链接、备注和面试回顾。日历与首页时间轴会汇总你的安排。', tip: '面试结束后，在编辑日程中补上面试回顾，之后就能在面试总结里整理复习。', visual: 'calendar' },
  { key: 'mail', section: '减少手工录入', title: '让招聘邮件进入工作流', description: '配置邮箱客户端授权后，CareerFlow 可以收取招聘邮件并识别公司、岗位、面试时间和流程变化等信息，帮你把邮件内容转成后续可处理的事项。', tip: '识别结果应先检查再确认；邮箱设置中可以查看连接状态与待处理邮件。', visual: 'mail' },
  { key: 'stats', section: '回顾进度', title: '用统计看求职过程', description: '统计页面从阶段、渠道和时间等角度汇总投递情况，让你快速了解机会分布和近期进展，也能发现需要调整的环节。', tip: '持续维护投递阶段，统计结果会更完整、更有参考价值。', visual: 'stats' },
  { key: 'interview', section: '积累经验', title: '把真实面试变成复习材料', description: '在完成的面试日程里记录问题和回顾，再到「面试总结」按项目经历、通用知识点和其他问题整理。相似问法会归纳到一起，并生成详细学习讲解。', tip: '个人主页可以补充教育、实习和项目经历，项目类讲解会结合对应经历生成。', visual: 'interview' },
  { key: 'team', section: '一起协作', title: '与小组成员共享求职进度', description: '创建或加入小组后，可和成员共同查看小组求职进度与日程。个人记录和小组协作各自保留，适合和同学互相提醒、交流经验。', tip: '使用小组功能前，请确认当前记录的可见范围符合你的需要。', visual: 'team' }
]
const index = ref(0)
const slide = computed(() => slides[index.value])
const progress = computed(() => ((index.value + 1) / slides.length) * 100)
function goTo(next: number) { index.value = Math.min(slides.length - 1, Math.max(0, next)) }
function onKeydown(event: KeyboardEvent) {
  if (event.altKey || event.ctrlKey || event.metaKey || event.target instanceof HTMLElement && ['INPUT', 'TEXTAREA', 'SELECT'].includes(event.target.tagName)) return
  if (event.key === 'ArrowRight') { event.preventDefault(); goTo(index.value + 1) }
  if (event.key === 'ArrowLeft') { event.preventDefault(); goTo(index.value - 1) }
}
onMounted(() => window.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => window.removeEventListener('keydown', onKeydown))
</script>

<template>
  <div class="guide-page" aria-labelledby="guide-title">
    <header class="guide-topline">
      <button type="button" class="guide-back" @click="emit('navigate', 'home')"><span aria-hidden="true">←</span> 返回主页</button>
      <span class="guide-kicker">CAREFLOW 使用指南</span>
      <span class="guide-count">{{ String(index + 1).padStart(2, '0') }} <i>/</i> {{ String(slides.length).padStart(2, '0') }}</span>
    </header>

    <div class="guide-progress" role="progressbar" :aria-valuenow="index + 1" :aria-valuemin="1" :aria-valuemax="slides.length" :aria-label="`第 ${index + 1} 页，共 ${slides.length} 页`"><span :style="{ width: `${progress}%` }"></span></div>

    <Transition name="guide-slide" mode="out-in">
      <article :key="slide.key" class="guide-slide">
        <section class="guide-copy">
          <span class="guide-section"><i>{{ String(index + 1).padStart(2, '0') }}</i>{{ slide.section }}</span>
          <h1 id="guide-title">{{ slide.title }}</h1>
          <p class="guide-description">{{ slide.description }}</p>
          <p class="guide-tip"><span aria-hidden="true">✦</span><span>{{ slide.tip }}</span></p>
          <div class="guide-controls">
            <button type="button" class="arrow-button previous" :disabled="index === 0" aria-label="上一页" @click="goTo(index - 1)"><span aria-hidden="true">←</span></button>
            <div class="guide-dots" aria-label="跳转到指引页面"><button v-for="(item, itemIndex) in slides" :key="item.key" type="button" :class="{ active: index === itemIndex }" :aria-label="`第 ${itemIndex + 1} 页：${item.section}`" :aria-current="index === itemIndex ? 'step' : undefined" @click="goTo(itemIndex)"></button></div>
            <button v-if="index < slides.length - 1" type="button" class="arrow-button next" aria-label="下一页" @click="goTo(index + 1)"><span aria-hidden="true">→</span></button>
            <button v-else type="button" class="finish-button" @click="emit('navigate', 'home')">开始使用 <span aria-hidden="true">↗</span></button>
          </div>
          <p class="keyboard-hint"><kbd>←</kbd><kbd>→</kbd> 也可以用键盘翻页</p>
        </section>

        <section class="guide-art" :class="`visual-${slide.visual}`" aria-label="功能示意图">
          <div class="art-window">
            <div class="art-window-bar"><span class="brand-mark">C</span><strong>CareerFlow</strong><span class="window-dots"><i></i><i></i><i></i></span></div>
            <div v-if="slide.visual === 'home'" class="mock-content home-mock"><div class="mock-heading"><small>周一 · 10月8日</small><strong>今天的求职安排</strong></div><div class="mini-stat-row"><div><small>进行中的机会</small><b>08</b></div><div><small>本周面试</small><b>03</b></div></div><div class="mock-timeline"><span class="timeline-line"></span><div><i class="dot purple"></i><small>14:50</small><b>去哪儿旅行 · HR面</b></div><div><i class="dot teal"></i><small>19:00</small><b>字节跳动 · 二面</b></div></div></div>
            <div v-else-if="slide.visual === 'applications'" class="mock-content application-mock"><div class="mock-heading"><small>投递记录</small><strong>我的机会 <em>8 个岗位</em></strong></div><div class="stage-line"><span v-for="stage in ['已投递','笔试','面试','Offer']" :key="stage">{{ stage }}</span></div><div class="application-row"><i class="company-logo">顺</i><div><b>顺丰科技</b><small>AI开发工程师 · 官网</small></div><span class="stage-pill">面试</span></div><div class="application-row"><i class="company-logo orange">字</i><div><b>字节跳动</b><small>后端开发工程师 · 内推</small></div><span class="stage-pill muted">笔试</span></div></div>
            <div v-else-if="slide.visual === 'calendar'" class="mock-content calendar-mock"><div class="mock-heading"><small>2026年10月</small><strong>本周安排</strong></div><div class="calendar-grid"><span v-for="day in ['一','二','三','四','五','六','日']" :key="day" class="weekday">{{ day }}</span><span v-for="day in 14" :key="day" :class="{ selected: day === 8, marked: [8, 9, 10].includes(day) }">{{ day }}</span></div><div class="calendar-event"><i></i><div><b>去哪儿旅行 · HR面</b><small>10月8日 · 14:50</small></div><span>面试</span></div></div>
            <div v-else-if="slide.visual === 'mail'" class="mock-content mail-mock"><div class="mock-heading"><small>招聘邮件识别</small><strong>确认识别结果</strong></div><div class="mail-paper"><div class="mail-subject">【顺丰科技】面试安排通知</div><p>你好，邀请你参加 AI 开发工程师岗位面试，请确认以下安排。</p><div class="recognized-grid"><span>公司<b>顺丰科技</b></span><span>面试轮次<b>二面</b></span><span>时间<b>10月8日 14:50</b></span><span>方式<b>视频面试</b></span></div></div><div class="mail-confirm"><span>识别完成，请核对信息</span><b>确认并加入日程　✓</b></div></div>
            <div v-else-if="slide.visual === 'stats'" class="mock-content stats-mock"><div class="mock-heading"><small>求职分析</small><strong>投递进度一览</strong></div><div class="stat-cards"><div><small>累计投递</small><b>24 <i>份</i></b></div><div><small>面试机会</small><b>08 <i>场</i></b></div><div><small>Offer</small><b>02 <i>个</i></b></div></div><div class="chart-title">各阶段机会分布</div><div class="bar-chart"><span v-for="(height, barIndex) in [45, 74, 55, 88, 34, 62, 48, 77, 59, 92, 43, 68]" :key="barIndex" :style="{ height: `${height}%` }"></span></div><div class="chart-labels"><small>已投递</small><small>笔试</small><small>面试</small><small>Offer</small></div></div>
            <div v-else-if="slide.visual === 'interview'" class="mock-content review-mock"><div class="mock-heading"><small>AI 面试复习</small><strong>把问题整理成知识库</strong></div><div class="review-columns"><div class="review-list-mock"><small>面试回顾</small><span>顺丰科技 · 二面</span><span>字节跳动 · 一面</span><span>携程集团 · 二面</span></div><div class="review-topics-mock"><small>考点分类</small><b>项目考点　12</b><b>八股考点　18</b><b>其他问题　4</b></div></div><div class="answer-mock"><b>JVM 与线上排查</b><p>考察内存结构、垃圾回收与常见线上问题定位。按原理、诊断流程和实践取舍展开复习……</p></div></div>
            <div v-else class="mock-content team-mock"><div class="mock-heading"><small>协作小组</small><strong>一起跟进求职进展</strong></div><div class="team-members"><span class="avatar lavender">周</span><span class="avatar aqua">林</span><span class="avatar amber">陈</span><div><b>求职小组</b><small>3 位成员 · 本周 6 项日程</small></div></div><div class="team-activity"><small>小组动态</small><p><i class="activity-dot"></i><span><b>林同学</b> 更新了面试安排<small>今天 10:32 · 星河科技一面</small></span></p><p><i class="activity-dot green"></i><span><b>你</b> 完成了本周日程<small>昨天 19:10 · 共 4 项</small></span></p></div><div class="team-footer"><span>投递进度</span><b>成员间同步更新　→</b></div></div>
          </div>
          <div class="art-caption"><span>CAREERFLOW GUIDE</span><span>{{ String(index + 1).padStart(2, '0') }} / {{ String(slides.length).padStart(2, '0') }}</span></div>
        </section>
      </article>
    </Transition>
  </div>
</template>

<style scoped>
.guide-page{--guide-accent:#a5adff;--guide-ink:#f4f5fb;--guide-muted:#a1a7b8;--guide-panel:#191c25;--guide-panel-soft:#222632;--guide-edge:#303544;display:flex;min-height:calc(100dvh - 32px);flex-direction:column;padding:22px 0 16px;color:var(--color-foreground)}
.guide-topline{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:12px;color:var(--color-muted-foreground);font-size:11px;font-weight:750;letter-spacing:.12em}.guide-back{justify-self:start;display:flex;align-items:center;gap:8px;min-height:42px;padding:7px 12px;border:1px solid var(--color-border);border-radius:9px;color:var(--color-foreground);background:var(--color-card);font-size:13px;font-weight:650;letter-spacing:0}.guide-back span{font-size:18px;line-height:1}.guide-back:hover,.arrow-button:hover:not(:disabled){border-color:var(--guide-accent);background:color-mix(in srgb,var(--guide-accent) 10%,var(--color-card))}.guide-kicker{color:var(--color-primary);text-align:center}.guide-count{justify-self:end;font-variant-numeric:tabular-nums;letter-spacing:.06em}.guide-count i{padding:0 5px;color:var(--color-border-strong);font-style:normal}.guide-progress{height:2px;margin:14px 0 22px;overflow:hidden;background:var(--color-border)}.guide-progress span{display:block;height:100%;border-radius:2px;background:var(--color-primary);transition:width .35s ease}
.guide-slide{display:grid;min-height:0;flex:1;grid-template-columns:minmax(300px,.78fr) minmax(420px,1.22fr);align-items:center;gap:clamp(36px,7vw,100px)}.guide-copy{max-width:470px;padding:10px 0 26px}.guide-section{display:inline-flex;align-items:center;gap:10px;margin-bottom:20px;color:var(--color-primary);font-size:13px;font-weight:750}.guide-section i{display:grid;width:28px;height:28px;place-items:center;border:1px solid color-mix(in srgb,var(--color-primary) 32%,transparent);border-radius:8px;background:color-mix(in srgb,var(--color-primary) 10%,transparent);font-size:11px;font-style:normal}.guide-copy h1{max-width:440px;margin:0 0 18px;font-size:clamp(30px,3.5vw,48px);line-height:1.18;letter-spacing:-.04em}.guide-description{margin:0;color:var(--color-muted-foreground);font-size:15px;line-height:1.9}.guide-tip{display:flex;gap:10px;margin:24px 0 28px;padding:13px 14px;border:1px solid color-mix(in srgb,var(--color-primary) 20%,var(--color-border));border-radius:10px;color:var(--color-muted-foreground);background:color-mix(in srgb,var(--color-primary) 5%,var(--color-card));font-size:13px;line-height:1.65}.guide-tip>span:first-child{flex:none;color:var(--color-primary)}.guide-controls{display:flex;align-items:center;gap:12px}.arrow-button{display:grid;width:44px;height:44px;flex:none;place-items:center;border:1px solid var(--color-border);border-radius:10px;color:var(--color-foreground);background:var(--color-card);font-size:22px;transition:background .18s,border-color .18s,transform .18s}.arrow-button:hover:not(:disabled){transform:translateY(-1px)}.arrow-button:disabled{opacity:.35}.guide-dots{display:flex;align-items:center;gap:7px;padding:0 5px}.guide-dots button{width:8px;height:8px;padding:0;border:0;border-radius:8px;background:var(--color-border-strong);transition:width .22s,background .22s}.guide-dots button.active{width:23px;background:var(--color-primary)}.finish-button{min-height:44px;padding:0 16px;border:0;border-radius:10px;color:var(--color-on-primary);background:var(--color-primary);font-weight:750}.finish-button span{padding-left:6px}.keyboard-hint{display:flex;align-items:center;gap:5px;margin:14px 0 0 2px;color:var(--color-muted-foreground);font-size:11px}.keyboard-hint kbd{display:inline-grid;min-width:19px;height:18px;place-items:center;border:1px solid var(--color-border);border-radius:4px;background:var(--color-card);font:inherit}
.guide-art{position:relative;min-width:0;padding:clamp(14px,3vw,34px);border:1px solid var(--color-border);border-radius:24px;background:radial-gradient(ellipse at 22% 10%,color-mix(in srgb,var(--color-primary) 14%,transparent),transparent 48%),linear-gradient(145deg,color-mix(in srgb,var(--color-card) 96%,transparent),var(--color-background));box-shadow:0 26px 80px rgb(0 0 0 / 18%)}.guide-art::before,.guide-art::after{position:absolute;z-index:0;content:'';border:1px solid color-mix(in srgb,var(--color-primary) 16%,transparent);border-radius:50%;pointer-events:none}.guide-art::before{inset:9% -12% auto auto;width:180px;height:180px}.guide-art::after{right:6%;bottom:-34px;width:72px;height:72px}.art-window{position:relative;z-index:1;min-height:430px;overflow:hidden;border:1px solid var(--color-border);border-radius:15px;color:var(--color-foreground);background:var(--color-background);box-shadow:0 14px 42px rgb(0 0 0 / 22%)}.art-window-bar{display:flex;height:44px;align-items:center;gap:9px;padding:0 14px;border-bottom:1px solid var(--color-border);background:var(--color-card)}.brand-mark{display:grid;width:22px;height:22px;place-items:center;border-radius:7px;color:white;background:linear-gradient(135deg,#35b7a8,#536be1);font-size:12px;font-weight:850}.art-window-bar strong{font-size:12px}.window-dots{display:flex;gap:4px;margin-left:auto}.window-dots i{width:6px;height:6px;border-radius:50%;background:var(--color-border-strong)}.mock-content{display:grid;gap:18px;padding:22px clamp(16px,3vw,32px)}.mock-heading{display:grid;gap:5px}.mock-heading>small{color:var(--color-primary);font-size:10px;font-weight:700}.mock-heading>strong{font-size:17px}.mock-heading em{float:right;color:var(--color-muted-foreground);font-size:10px;font-style:normal;font-weight:500}.mini-stat-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.mini-stat-row>div,.stat-cards>div{display:grid;gap:6px;padding:13px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-card)}.mini-stat-row small,.stat-cards small{color:var(--color-muted-foreground);font-size:10px}.mini-stat-row b{font-size:24px}.mock-timeline{position:relative;display:grid;gap:13px;padding:2px 0 0 12px}.timeline-line{position:absolute;top:7px;bottom:10px;left:4px;width:1px;background:linear-gradient(var(--color-primary),#52b49b)}.mock-timeline>div{position:relative;display:grid;grid-template-columns:46px 1fr;gap:5px 10px;align-items:center}.mock-timeline>div small{color:var(--color-muted-foreground);font-size:10px}.mock-timeline>div b{font-size:12px}.dot{position:absolute;top:5px;left:-12px;width:9px;height:9px;border:2px solid var(--color-background);border-radius:50%;background:var(--color-primary)}.dot.teal{background:#4cb99a}
.stage-line{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.stage-line span{position:relative;padding:8px 3px;border-radius:6px;color:var(--color-muted-foreground);background:var(--color-card);font-size:9px;text-align:center}.stage-line span:nth-child(-n+3){color:var(--color-primary)}.application-row{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-card)}.company-logo{display:grid;width:31px;height:31px;flex:none;place-items:center;border-radius:9px;color:white;background:#35a88e;font-size:12px;font-style:normal;font-weight:800}.company-logo.orange{background:#dd8d4e}.application-row>div{display:grid;min-width:0;flex:1;gap:4px}.application-row b{font-size:12px}.application-row small{overflow:hidden;color:var(--color-muted-foreground);font-size:10px;text-overflow:ellipsis;white-space:nowrap}.stage-pill{padding:4px 7px;border-radius:20px;color:#fff;background:#5f83db;font-size:9px}.stage-pill.muted{color:var(--color-muted-foreground);background:var(--color-muted)}
.calendar-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:6px;text-align:center}.calendar-grid span{display:grid;min-height:25px;place-items:center;border-radius:7px;color:var(--color-muted-foreground);font-size:10px}.calendar-grid .weekday{min-height:18px;color:var(--color-primary);font-size:9px;font-weight:700}.calendar-grid span.marked{color:var(--color-foreground);background:color-mix(in srgb,var(--color-primary) 10%,var(--color-card))}.calendar-grid span.selected{color:var(--color-on-primary);background:var(--color-primary)}.calendar-event{display:flex;align-items:center;gap:10px;padding:11px;border:1px solid var(--color-border);border-radius:9px;background:var(--color-card)}.calendar-event>i{width:8px;height:8px;border-radius:50%;background:#5bb895}.calendar-event>div{display:grid;flex:1;gap:4px}.calendar-event b{font-size:11px}.calendar-event small{color:var(--color-muted-foreground);font-size:9px}.calendar-event>span{color:var(--color-primary);font-size:9px}
.mail-paper{padding:15px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-card)}.mail-subject{padding-bottom:10px;border-bottom:1px solid var(--color-border);font-size:12px;font-weight:750}.mail-paper>p{color:var(--color-muted-foreground);font-size:10px;line-height:1.6}.recognized-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.recognized-grid>span{display:grid;gap:3px;padding:7px;border-radius:6px;background:color-mix(in srgb,var(--color-primary) 7%,var(--color-card));color:var(--color-muted-foreground);font-size:9px}.recognized-grid b{color:var(--color-foreground);font-size:10px}.mail-confirm{display:flex;align-items:center;justify-content:space-between;gap:8px;color:var(--color-muted-foreground);font-size:9px}.mail-confirm b{padding:8px;border-radius:7px;color:var(--color-on-primary);background:#55ad8c;font-size:9px}
.stat-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.stat-cards>div{padding:11px}.stat-cards b{font-size:19px}.stat-cards b i{color:var(--color-muted-foreground);font-size:9px;font-style:normal;font-weight:500}.chart-title{margin-bottom:-13px;font-size:10px;font-weight:700}.bar-chart{display:flex;height:112px;align-items:end;justify-content:space-between;gap:7px;padding:8px 10px 0;border-bottom:1px solid var(--color-border);background:repeating-linear-gradient(to top,transparent 0,transparent 27px,color-mix(in srgb,var(--color-border) 65%,transparent) 28px)}.bar-chart span{width:6%;border-radius:5px 5px 0 0;background:linear-gradient(0deg,color-mix(in srgb,var(--color-primary) 48%,#38b49e),var(--color-primary));opacity:.83}.bar-chart span:nth-child(3n){opacity:.57}.chart-labels{display:flex;justify-content:space-between;color:var(--color-muted-foreground);font-size:9px}
.review-columns{display:grid;grid-template-columns:1.15fr .85fr;gap:11px}.review-list-mock,.review-topics-mock{display:grid;align-content:start;gap:8px;padding:12px;border:1px solid var(--color-border);border-radius:9px;background:var(--color-card)}.review-list-mock>small,.review-topics-mock>small{margin-bottom:2px;color:var(--color-muted-foreground);font-size:9px}.review-list-mock>span{overflow:hidden;padding:8px;border-radius:6px;background:var(--color-background);font-size:9px;text-overflow:ellipsis;white-space:nowrap}.review-topics-mock>b{padding:8px;border-radius:6px;color:var(--color-primary);background:color-mix(in srgb,var(--color-primary) 9%,var(--color-background));font-size:9px}.answer-mock{padding:13px;border-left:2px solid var(--color-primary);border-radius:7px;background:color-mix(in srgb,var(--color-primary) 6%,var(--color-card))}.answer-mock>b{font-size:11px}.answer-mock>p{margin:7px 0 0;color:var(--color-muted-foreground);font-size:10px;line-height:1.7}.team-members{display:flex;align-items:center;padding:14px;border:1px solid var(--color-border);border-radius:10px;background:var(--color-card)}.avatar{display:grid;width:33px;height:33px;place-items:center;border:2px solid var(--color-card);border-radius:50%;color:white;font-size:10px;font-weight:750}.avatar+.avatar{margin-left:-8px}.avatar.lavender{background:#8175ce}.avatar.aqua{background:#32a18f}.avatar.amber{background:#c88748}.team-members>div{display:grid;gap:4px;margin-left:10px}.team-members b{font-size:11px}.team-members small,.team-activity>small{color:var(--color-muted-foreground);font-size:9px}.team-activity{display:grid;gap:2px;padding:12px;border:1px solid var(--color-border);border-radius:10px}.team-activity>small{margin-bottom:5px}.team-activity p{display:flex;align-items:flex-start;gap:9px;margin:0;padding:8px 0;border-top:1px solid var(--color-border)}.activity-dot{width:7px;height:7px;flex:none;margin-top:4px;border-radius:50%;background:var(--color-primary)}.activity-dot.green{background:#55ad8c}.team-activity p>span{display:grid;gap:4px;color:var(--color-muted-foreground);font-size:10px}.team-activity b{color:var(--color-foreground)}.team-activity p small{font-size:9px}.team-footer{display:flex;justify-content:space-between;padding:10px;border-radius:8px;background:color-mix(in srgb,var(--color-primary) 7%,var(--color-card));font-size:9px}.team-footer span{color:var(--color-muted-foreground)}.team-footer b{color:var(--color-primary)}
.art-caption{position:relative;z-index:1;display:flex;justify-content:space-between;margin-top:13px;color:var(--color-muted-foreground);font-size:9px;font-weight:700;letter-spacing:.1em}.guide-slide-enter-active,.guide-slide-leave-active{transition:opacity .18s ease,transform .18s ease}.guide-slide-enter-from{transform:translateX(12px);opacity:0}.guide-slide-leave-to{transform:translateX(-12px);opacity:0}
@media(max-width:1000px){.guide-page{min-height:calc(100dvh - 108px)}.guide-slide{grid-template-columns:minmax(240px,.8fr) minmax(320px,1.2fr);gap:26px}.art-window{min-height:390px}.mock-content{gap:14px;padding:18px}.guide-description{font-size:14px}}
@media(max-width:720px){.guide-page{min-height:calc(100dvh - 100px);padding:8px 0}.guide-topline{grid-template-columns:1fr auto}.guide-kicker{display:none}.guide-slide{grid-template-columns:1fr;gap:22px}.guide-copy{order:2;max-width:none;padding:0}.guide-art{order:1;padding:12px;border-radius:17px}.art-window{min-height:300px}.mock-content{gap:12px;padding:15px}.guide-section{margin-bottom:11px}.guide-copy h1{margin-bottom:10px;font-size:clamp(27px,7vw,38px)}.guide-description{font-size:13px;line-height:1.72}.guide-tip{margin:14px 0;padding:10px 12px}.guide-controls{gap:9px}.guide-progress{margin:10px 0 16px}.calendar-grid{gap:3px}.calendar-grid span{min-height:21px}.bar-chart{height:86px}}
@media(prefers-reduced-motion:reduce){.guide-progress span,.guide-dots button,.arrow-button,.guide-slide-enter-active,.guide-slide-leave-active{transition:none}.guide-slide-enter-from,.guide-slide-leave-to{transform:none}}
</style>
